Spanish blueprint doc
cisco/mindmeld pull request #259
Opened 2020-12-09 21:39 UTC by lfiedlerc

Documentation for the Spanish screenin app

2020-12-11 18:53 UTC, serapio requested changes

2020-12-11 18:53 UTC, serapio commented on source/blueprints/screening_app.rst
> + - passes the object to the MindMeld Application Manager to a simulate an external user interaction with the app, and
```suggestion
 - passes the object to the MindMeld Application Manager to simulate an external user interaction with the app, and
```

2020-12-11 18:53 UTC, serapio commented on source/blueprints/screening_app.rst
> +   - learn non-system entities
```suggestion
   - learn custom entities
```

2020-12-14 18:23 UTC, vembar commented on source/blueprints/screening_app.rst
> +In this step-by-step walkthrough, you'll build a conversational application for a health screening that allows users to identify their risk of prediabetes.
"...for a health screening that..." --> "...for a health screening application that.."

2020-12-14 18:27 UTC, ritvikshrivastava commented on source/blueprints/screening_app.rst
> +   Please make sure to install and run all of the :ref:`pre-requisites <getting_started_virtualenv_setup>` for MindMeld before continuing on with this blueprint tutorial.
```suggestion
   Please make sure to install and run all of the :ref:`pre-requisites <getting_started_virtualenv_setup>` for MindMeld before continuing with this blueprint tutorial.
```

2020-12-14 18:29 UTC, ritvikshrivastava commented on source/blueprints/screening_app.rst
> +The conversational flows for a health screening will primarily involve asking users a series of questions about their medical history relevant to prediabetes. Once all necessary questions have been a
```suggestion
The conversational flows for a health screening will primarily involve asking users a series of questions about their medical history relevant to prediabetes. Once all necessary questions have been answered, the users are informed of their risk for presenting prediabetes.
```

2020-12-14 18:29 UTC, vembar commented on source/blueprints/screening_app.rst
> +The conversational flows for a health screening will primarily involve asking users a series of questions about their medical history relevant to prediabetes. Once all necessary questions have been a
The conversational flows for ~~a~~ health screening will primarily ...

2020-12-14 18:35 UTC, ritvikshrivastava commented on source/blueprints/screening_app.rst
> +The ``@app.dialogue_flow`` decorator designates the flow's entry point. Once inside, every follow up turn will continue to be in this flow until we exit the flow. If the user tries to disrupt the flo
```suggestion
The ``@app.dialogue_flow`` decorator designates the flow's entry point. Once inside, every follow up turn will continue to be in this flow until we exit the flow. If the user response disrupts the flow by answering something unrelated to the prompt, we gently reprompt the user to provide an answer for the current question. We can further control how the screening progresses by setting the ``allowed_intents`` attribute of the params object in the dialogue state handler. This attribute specifies a list of intents that you can set to force the language processor to choose from.
```

2020-12-14 18:42 UTC, vembar commented on source/blueprints/screening_app.rst
> +   Experiment with different models, features, and hyperparameter selection settings to see how they affect classifier performance. Maintain a held-out validation set to evaluate your trained NLP mod
"Maintain a held-out validation set to evaluate your trained NLP models and analyze misclassified ~~test~~ instances."

Just so we are clear that we only analyze errors on the validation set and not the test set.

2020-12-14 18:46 UTC, vembar commented on source/blueprints/screening_app.rst
> +There are two types of entities in MindMeld: :ref:`System Entities <system-entities>` and :doc:`Custom Entities <../userguide/entity_recognizer>`. System entities are pre-defined in MindMeld. Example
Should we clarify that the gazetteer offers a strong signal and does not mean we can identify only those entity values?

2020-12-14 22:50 UTC, serapio approved these changes

2020-12-14 22:50 UTC, merged